config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: "welcome#home"
  resources :surveys, only: [:new, :create]
  resources :personalities, except: [:destroy, :index]
  resources :users, only: [:show, :edit, :update]
  resources :projects, only: [:index]

  delete '/users/:user_id/projects/:id', to: 'projects#destroy', as: :delete_project_path

  resources :users do
    resources :projects, except: [:index]
  end

  get '/users/:user_id/projects', to: "projects#public"

  #you can change the route that POSTs to ProjectMembers
  post '/project/:project_id/member/:id', to: "project_members#create", as: :project_member
  post '/project/:project_id/member/:id/update', to: "project_members#update", as: :edit_project_member

  # Catch-all route, redirects to root
  match '*path', to: redirect('/'), via: :all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :owned_projects, class_name: 'Project', foreign_key: 'manager_id'
  has_many :project_members
  has_many :projects, through: :project_members
  has_many :responses
  has_many :questions, through: :responses
  has_one :personality

  def project_matches
    self.project_members.where(status: "pending")
  end

  def accepted_matches
    self.project_members.where(status: "accepted")
  end

  def awaiting_reply(project_id)
    self.project_matches.where(project_id: project_id)
  end

  def accepted?(project)
    proj = self.project_members.where(project_id: project.id).first
    !proj.nil? && proj.status == "accepted"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show
    @user = User.find_by(id: params[:id])
    @matches = @user.project_matches
    if @user.personality
      @personality_type = @user.personality.type
      @personality_url = @user.personality.type_url
    else
      @personality_type = "Take the Test"
      @personality_url = "/personalities/new"
    end
    return redirect_to users_path unless @user == current_user
    respond_to do |format|
      format.html {} # implicit rendering
      format.json do
        # render user, including all owned projects and projects
        render json: @user, adapter: :json
      end
    end
  end
end

app/views/users/show.html.erb
<div class="container">
  <h1 class="username"><%= "#{@user.first_name} #{@user.last_name}" %>'s Profile</h1><br>
  <h3>Your Personality Type: <%= link_to @personality_type, @personality_url %></h3>
  <hr />

  <div id="matches">
    <% if @matches %>

      <h3>Recommended Projects: </h3>
      <h4>These projects match what you are looking for<h4>
      <% @matches.each do |match| %>
        <%= link_to match.project.name, user_project_path(@user, match.project) %><br>
      <% end %>
    <% end %>
    <hr />
  </div>

  <h3>My Projects</h3>

  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#managed-projects">Managed Projects</a></li>
    <li><a data-toggle="tab" href="#projects">Projects</a></li>
  </ul>

  <div class="tab-content">
    <div id="managed-projects" class="tab-pane active">
    </div>

    <div id="projects" class="tab-pane">
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    getProjects(<%= @user.id %>)
  })
</script>