config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: "welcome#home"
  resources :surveys, only: [:new, :create]
  resources :personalities, except: [:destroy, :index]
  resources :users, only: [:show, :edit, :update]
  resources :projects, only: [:index]

  delete '/users/:user_id/projects/:id', to: 'projects#destroy', as: :delete_project_path

  resources :users do
    resources :projects, except: [:index]
  end

  get '/users/:user_id/projects', to: "projects#public"

  #you can change the route that POSTs to ProjectMembers
  post '/project/:project_id/member/:id', to: "project_members#create", as: :project_member
  post '/project/:project_id/member/:id/update', to: "project_members#update", as: :edit_project_member

  # Catch-all route, redirects to root
  match '*path', to: redirect('/'), via: :all
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :manager, class_name: 'User'
  has_many :project_members
  has_many :members, through: :project_members, source: :member
  validates :name, presence: true
  has_one :survey
  accepts_nested_attributes_for :survey


  def question_ids=(array)
    array.reject! { |x| x.empty? }
    array.each do |id|
      self.question_ids << id.to_i
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_manager, only: [:new, :create, :index, :public]
  before_action :set_project, only: [:show]

  def index
    @projects = Project.all
  end

  def show
    @manager = User.find_by(id: params[:user_id])
    @project = Project.find_by(id: params[:id])

    @matches = []
    @project.survey.responses.map do |resp|
      q = resp.question
      @matches << q.member_responses.where(answer: resp.answer)
      @matched = @matches.flatten.delete_if { |x| x.user_id == @manager.id }
    end
    x = []
    if @matched != nil
      @matched.flatten.each do |resp|
        x << resp.user
      end
      @names = x.uniq
    end
  end

  def public
    @projects = @manager.owned_projects
  end

  def new
    @project = @manager.owned_projects.build
    # @questions = Question.all
    @survey = Survey.new

    @survey.questions = Question.all
    @responses = @survey.responses
    @checkboxes = (1..5).to_a
    # @questions.each do |q|
    #   @survey.responses.build(question_id: q.id, user_id: current_user.id)
    # end
  end

  def create
    @manager = current_user
    @project = @manager.owned_projects.build(project_params)
    @project.save
    @survey = Survey.create(project_id: @project.id)

    survey_params.values.each do |resp|
      x = Response.new(question_id: resp[:question_id], answer: resp[:answer], importance: resp[:importance], user_id: current_user.id)
      @survey.responses << x
    end
    @survey.save
    if @project.save
      redirect_to user_project_path(current_user, @project)
    else
      render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def set_manager
    @manager = User.find_by(id: params[:user_id])
  end

  def set_project
    @project = Project.find_by(id: params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def survey_params
    params[:project][:survey][:responses_attributes]
  end

end

app/views/projects/index.html.erb
<div class="container">
  <h1>Browse Projects</h1>

  <% @projects.each do |project| %>
    <h3><%= link_to "#{project.name}", user_project_path(project.manager_id, project) %></h3>
    <%= project.manager.first_name %>
    created: <%= project.created_at %>
    <p> <%= project.description %><br> </p>

  <% end %>

</div>

app/views/projects/new.html.erb
<h3 class="text-center">Create a New Project</h3>

<%= form_for [@manager, @project], url: '/users/:user_id/projects', method: 'post' do |f| %>
  <div class="form-group">
    <%= f.label :name %> <br />
    <%= f.text_field :name, required: 'required'  %> <br />
  </div>
  <div class="form-group">
    <%= f.label :description %> <br />
    <%= f.text_area :description, class: 'form-control', rows: '4' %> <br /><br>
  </div>
  <div class="form-group">
    
  </div>

  <%= f.fields_for @survey do |h| %>
    <%= h.fields_for :responses do |r| %>
      <%= r.hidden_field :question_id %><br>
      <%= r.hidden_field :user_id %>
      <%= r.object.question.text %><br>
      <%= label :answer, "True", value: true %>
      <%= r.radio_button :answer, true %>
      <%= label :answer, "False", value: false %>
      <%= r.radio_button :answer, false %><br>
      Importance: <%= r.collection_radio_buttons(:importance, @checkboxes, :to_i, :to_i) %><br><br>
    <% end %>
  <% end %><br>
  <%= f.submit class: 'btn btn-primary'%>

<% end %>

app/views/projects/public.html.erb
<h3> Projects under the direction of <%= @manager.first_name%> <%= @manager.last_name%></h3>

<% @projects.each do |project| %>
  <h4><%= project.name %></h4>
    <%= project.description %>...
    <%= link_to 'learn more', user_project_path(@manager, project)%>
  <% if @manager == current_user %>
    <%= link_to '[edit]' %>
  <% end %> <br><br>

<% end %>



<br><br>
<%= link_to 'all projects', projects_path %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<h3><%= @project.description %></h3>
<h3>Manager: <%= link_to "#{@project.manager.first_name} #{@project.manager.last_name}" %></h3><br>


<% if current_user == @project.manager %>
  <h4>Recommended matches:</h4>
  <% if @names == nil %>
    There are no current matches for this project.
  <% else %>
    <% @names.each do |name| %>
      <%= link_to "#{name.first_name} #{name.last_name}", project_member_path(@project, name), method: :post %>
      <% if !name.awaiting_reply(@project).empty? %>
        Requested
      <% elsif name.accepted?(@project) %>
        Accepted
      <% end %><br>
    <% end %>
  <% end %>
<% end %>

<% if current_user.project_members.find_by(project_id: @project.id) && current_user.project_members.find_by(project_id: @project.id).status == "pending" %>
  <%= link_to 'Accept', edit_project_member_path(@project.id, current_user.id), method: :post %>
<% end %>